### ISSUE TITLE
Is this project still in development?

### ISSUE THREAD

**Issue by Alfred-Mountfield** [bheisler/iai#27]
Hello, just wondering if this project is still active or in development? 

It seemed really promising for repeatable benchmarks in CI so it'd be good to know if it's unlikely to be developed further.

**Comment by bheisler** [comment]
I'd say it's in that twilight zone of "not definitively abandoned but not actively maintained at this time, but if I find the time and energy it could be more actively maintained in the future".

**Comment by Alfred-Mountfield** [comment]
That makes sense, definitely a shame at this time though. It's an awesome project and I have high-hopes for how useful it could be in the future.

I hope you find time and energy at some point! (I'd offer to help but it's a bit out of my wheelhouse)
